version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: .docker/apache.dockerfile
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      #not override in container /app/node_modules
      - /app/node_modules
      - ./app:/var/www/html
      - ./data/etc/apache2/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./data/log/apache2/access.log:/var/log/apache2/access.log
      - ./data/log/apache2/error.log:/var/log/apache2/error.log
    ports:
      - 8070:80
    depends_on:
      - db
    working_dir: /var/www/html
    networks:
      - apache-net

  db:
    image: mariadb
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./data/backup:/data/backup
    networks:
      - apache-net

  adminer:
    depends_on:
      - db
    image: adminer
    # restart: always
    ports:
      - 6080:8080
    networks:
      - apache-net  

networks:
  apache-net:
    driver: "bridge"
